shop2/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shop.Models;
namespace shop.Controllers
{
    [Authorize(Roles = RolesName.canManageProduct)]
    public class CategoryController : Controller
    {
        private ApplicationDbContext _context;
      
        public CategoryController()
        {
            _context = new ApplicationDbContext();
        }
        public ActionResult New()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Category category)
        {
            _context.Categories.Add(category);
            _context.SaveChanges();            
            return View("FinalMessage");
        }
    }
}

shop2/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shop.Models;
using shop.ViewModels;
using Rotativa;

namespace shop.Controllers
{
    [Authorize(Roles = RolesName.canManageProduct)]
    public class OrdersController : Controller
    {
        private ApplicationDbContext _context;

        public OrdersController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Orders       
        public ActionResult OrdersList()
        {
            OrdersListViewModel viewmodel = new OrdersListViewModel { Categories = _context.Categories.ToList(), Products= _context.Products.ToList() };
            return View(viewmodel);            
        }
        
        public ActionResult OrdersListForPrint(int id)
        {
            Order order = _context.Orders.Single(o => o.Id==id);           
            return new ViewAsPdf("OrdersListForPrint", order);
        }
    }
}

shop2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Shopping</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shopping", "New", "Shopping", new { area = "" }, new { @class = "navbar-brand" })             
                @Html.ActionLink("Register a user", "Register", "Account")
                @Html.ActionLink("Products", "New", "Products")
                @Html.ActionLink("LogOff", "LogOff", "Account")
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
          
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

shop2/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Computer Repair</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your keywords">
    <meta name="author" content="Your name">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />

    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href="~/css/font-awesome.css" rel="stylesheet">
    <link href="~/css/camera.css" rel="stylesheet">
    <link href="~/css/touchTouch.css" rel="stylesheet">
    <link href="~/css/isotope.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">

    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/superfish.js"></script>

    <script src="~/js/jquery.queryloader2.js"></script>

    <script src="~/js/jquery.ui.totop.js"></script>
    <script src="~/js/jquery.equalheights.js"></script>

    <script src="~/js/jquery.parallax-1.1.3.resize.js"></script>

    <script src="~/js/SmoothScroll.js"></script>

    <script src="~/js/touchTouch.jquery.js"></script>
    <script src="~/js/jquery.isotope.min.js"></script>

    <script src="~/js/jquery.mobile.customized.min.js"></script>
    <script src="~/js/camera.js"></script>

    <script src="~/js/cform.js"></script>

    <script src="~/js/scripts.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="onepage front" data-spy="scroll" data-target="#top1" data-offset="81">
    <div id="main">

        <div id="top1">
            <div class="container">

                <header><div class="logo_wrapper"><a href=@Url.Action("Index", "Home") class="logo scroll-to"><img src="~/images/logo.png" alt="" class="img-responsive-old"></a></div></header>

                <div class="navbar navbar_ navbar-default">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-collapse navbar-collapse_ collapse">
                        <ul class="nav navbar-nav sf-menu clearfix">
                            <li class="active"><a href=@Url.Action("Index", "Home")>Home</a></li>

                            <li class="sub-menu sub-menu-1">
                                <a href=@Url.Action("New", "Shopping")>Shopping</a>
                                <ul>
                                    <li><a href=@Url.Action("New", "Shopping")>First More Page</a></li>
                                    <li><a href=@Url.Action("Index", "Home")>Second More Page</a></li>
                                </ul>
                            </li>
                            <li class="sub-menu sub-menu-1">
                                <a href=@Url.Action("New", "Products")>Products</a>
                            </li>
                            <li class="sub-menu sub-menu-1">
                                <a href=@Url.Action("New", "Category")>Categories</a>
                            </li>
                            <li class="sub-menu sub-menu-1">
                                <a href=@Url.Action("OrdersList", "Orders")>Orders List</a>
                            </li>
                            <li class="sub-menu sub-menu-1">
                                <a href=@Url.Action("Register", "Account")>Register</a>
                            </li>
                            
                            <li><a href="#contacts">Contacts</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <div id="home">
            <div class="container body-content">
                @RenderBody()
            </div>
            
        </div>

             

        <div id="contacts">
            <div id="contacts1">
                <div class="container">

                    <h2>Contact Us</h2>

                    <div class="time1_wrapper"><div class="time1 clearfix"><i class="fa fa-clock-o"></i><span><div class="txt1">1 800 123 456</div><div class="txt2">Mon - Fri: 10am-7pm<br>Sat: 10am-5pm<br>Sun: 9am-1pm</div></span></div></div>

                </div>
            </div>
            <div id="contacts2">
                <div class="container">
                    <div class="col-sm-4">

                        <h3>Contact Information</h3>

                        <div class="thumb1">
                            <div class="thumbnail">
                                <figure><img src="images/contacts01.jpg" alt=""></figure>
                                <div class="caption">
                                    <p>
                                        8901 Marmora Road,<br>Glasgow, D04 89GR.
                                    </p>
                                    <div class="phone3_wrapper"><div class="phone3 clearfix"><i class="fa fa-mobile"></i><span>+1 800 123 1234</span></div></div>
                                    <div class="mail1_wrapper"><div class="mail1 clearfix"><i class="fa fa-envelope-o"></i><span><a href="#">mail@demosite.com</a></span></div></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-sm-7 col-sm-offset-1">

                        <h3>Contact Form</h3>

                        <div id="note"></div>
                        <div id="fields">
                            <form id="ajax-contact-form" class="form-horizontal" action="javascript:alert('success!');">
                                <div class="row">
                                    <div class="col-sm-5">
                                        <div class="form-group">
                                            <label for="inputName">Your Name</label>
                                            <input type="text" class="form-control" id="inputName" name="name" value="Full Name" onBlur="if(this.value=='') this.value='Full Name'" onFocus="if(this.value =='Full Name' ) this.value=''">
                                        </div>
                                    </div>
                                    <div class="col-sm-5">
                                        <div class="form-group">
                                            <label for="inputEmail">Email</label>
                                            <input type="text" class="form-control" id="inputEmail" name="email" value="E-mail address" onBlur="if(this.value=='') this.value='E-mail address'" onFocus="if(this.value =='E-mail address' ) this.value=''">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-5">
                                        <div class="form-group">
                                            <label for="inputPhone">Phone</label>
                                            <input type="text" class="form-control" id="inputPhone" name="phone" value="Phone" onBlur="if(this.value=='') this.value='Phone'" onFocus="if(this.value =='Phone' ) this.value=''">
                                        </div>
                                    </div>
                                    <div class="col-sm-5">
                                        <div class="form-group">
                                            <label for="inputHow">How did you hear about us?</label>
                                            <select class="form-control" id="inputHow" name="how">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="inputMessage">Your Message</label>
                                            <textarea class="form-control" rows="5" id="inputMessage" name="content" onBlur="if(this.value=='') this.value='Message'"
                                                      onFocus="if(this.value =='Message' ) this.value=''">Message</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group capthca">
                                            <label for="inputCapthca" class="sr-only">Capthca</label>
                                            <input type="text" class="form-control" id="inputCapthca" name="capthca" value="Capthca" onBlur="if(this.value=='') this.value='Capthca'" onFocus="if(this.value =='Capthca' ) this.value=''">
                                        </div>
                                        <div class="form-group img">
                                            <img src="captcha/captcha.php">
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn-default btn-cf-submit">Submit</button>
                            </form>
                        </div>




                    </div>
                </div>
            </div>
            
        </div>

        <div id="bot1">
            <div class="container">
                <div class="bot1_inner clearfix">

                    <div class="menu_bot">
                        <ul id="menu_bot" class="clearfix">
                            <li><a href="#home">home</a></li>
                            <li><a href="#services">services</a></li>
                            <li><a href="#packages">packages</a></li>
                            <li><a href="#about">about</a></li>
                            <li><a href="#gallery">gallery</a></li>
                            <li><a href="#contacts">contacts</a></li>
                        </ul>
                    </div>

                    <div class="social_wrapper_bot">
                        <ul class="social clearfix">
                            <li><a href="#"><i class="fa fa-vimeo-square"></i></a></li>
                            <li><a href="#"><i class="fa fa-skype"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                            <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                            <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>

        <footer>
            <div class="container">
                <div class="footer_inner clearfix">

                    <div class="copy1">Copyright &copy; 2021 <a href="https://gridgum.com">GRIDGUM</a> All rights reserved.</div>

                    <div class="copy2"><a href="more.html">Privacy Policy</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="more.html">Terms of use</a></div>

                </div>
            </div>
        </footer>

    </div>

   
    <script src="js/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>