shop2/Controllers/Api/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Data.Entity;
using System.Net.Http;
using System.Web.Http;
using shop.Models;
using shop.Dtos;
using AutoMapper;


namespace shop.Controllers.Api
{
    public class ShoppingController : ApiController
    {
        [HttpPut]
        public void SaveInSession(int id,OrderDto orderDto)
        {
            List<Order> ordersList = new List<Order>();
            var order = Mapper.Map<OrderDto, Order>(orderDto);
            //order.CustomerId = 1;
            order.Date = DateTime.Now;
            ordersList.Add(order);            
            //Session["orders"] = ordersList;
           
        }
    }
}

shop2/Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using shop.Models;
using shop.ViewModels;

namespace shop.Controllers
{
    public class ShoppingController : Controller
    {
        private ApplicationDbContext _context;
        private List<Order> ordersList;
        public ShoppingController()
        {
            _context = new ApplicationDbContext();          
        }
        [AllowAnonymous]
        public ActionResult New()
        {
            var categories = _context.Categories.ToList();
            var viewModel = new NewProductViewModel()
            {
                Categories = categories
            };
            return View(viewModel);
        }
        [AllowAnonymous]
        [HttpPost]
        public void SaveInSession(Order order)
        {                    
            if(Session["orders"] != null)
            {
                bool oderExists = false;
               ordersList=(List<Order>)Session["orders"];
                foreach (Order sessionOrder in ordersList)
                {
                    if (sessionOrder.ProductId == order.ProductId)
                    {
                        sessionOrder.Count += order.Count;
                        oderExists = true;
                    }
                }
                if (!oderExists)
                {
                    ordersList.Add(order);
                }
            }
            else
            {
                ordersList = new List<Order>();                
                ordersList.Add(order);
            }      
            Session["orders"] = ordersList;           
        }
             
        [AllowAnonymous]
        public ActionResult ShowOrders()
        {
            if (Session["orders"] != null)
            {
              List<Order> ordersList = (List<Order>)Session["orders"];
              List<Product> products=_context.Products.ToList();
              List<string> productsName= new List<string>();          
              foreach (Order order in ordersList)
              {
                foreach(Product product in products)
                {
                    if (order.ProductId == product.Id)
                    {
                        productsName.Add(product.Name);
                    }
                }
            }
              OrdersViewModel ordersViewModel = new OrdersViewModel() { Orders = ordersList, ProductsName = productsName };
              return View(ordersViewModel);
            }
            else
            {
                var categories = _context.Categories.ToList();
                var viewModel = new NewProductViewModel()
                {
                    Categories = categories
                };
                return View("New", viewModel);
            }           
        }
        public ActionResult SaveOrdersInDB()
        {
            if (Session["orders"] != null)
            {
                List<Order> ordersList = (List<Order>)Session["orders"];
                if (ordersList.Count > 0)
                {                    
                    foreach (Order order in ordersList)
                    {
                        order.CustomerEmail = (String)Session["customerEmail"]; 
                        order.Date = DateTime.Now;
                        _context.Orders.Add(order);
                    }
                    _context.SaveChanges();                  
                }
                Session["orders"] = null;
            }
            return View("FinalMessage");
        }

    }    
}

shop2/Views/Shopping/FinalMessage.cshtml
@{
    ViewBag.Title = "FinalMessage";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Confirmed Order</h2>

<p> Your Order is Successfully submitted </p>
<a href='@Url.Action("New", "Shopping")'> Back to order page</a>

shop2/Views/Shopping/New.cshtml
@model shop.ViewModels.NewProductViewModel
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<div class="logo_wrapper"><a href="@Url.Action("ShowOrders", "Shopping")" class="logo scroll-to"><img src="~/images/trolly.png" alt="" class="img-responsive-old"></a></div>
<br />
<div class="form-group">
    <label for="Product_CategoryId">Category</label>
    @Html.DropDownListFor(m => m.Product.CategoryId, new SelectList(Model.Categories, "Id", "Name"), "Select Category Name", new { @class = "form-control" })
</div>
<br />
<button id="show" class="btn btn-primary"> Show Items by Category</button>
<br />
<div id="itemlist">
</div>
<br />

@section scripts{
    <script>              
        $(document).ready(function () {
            var button = null;            
        });
        function listmaker(name, price, available, details, imagename, id) {
            return ('<table class="table table-bordered table-hover"><tr><td>Product Name:</td><td>' + name + '</td></tr><tr><td>Price:</td><td>' + price + '</td></tr><tr><td>Available:</td><td>' + available + '</td></tr><tr><td>Details:</td><td>' + details + '</td></tr><tr><td>Image:</td><td><img style="width:200px;height:300px;" src="/UploadImage/' + imagename + '"></td></tr><tr><td>Count to Buy:</td><td><input type="text" id="textbox_' + id + '"></td></tr><tr><td><label id="message_' + id + '"></label></td><td><button id="btn_' + id + '">Add to Bascket</button></td></tr></table>');
        }
        function messages(productId, content, color) {
            $("#message_" + productId).text(content);
            $("#message_" + productId).css('color', color);
        }
        $("#show").on("click", function (e) {
            e.preventDefault();
            $.ajax({
                url: "/api/products",
                type: "GET",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    document.getElementById("itemlist").innerHTML = "";
                    $.each(data, function (i) {
                        if (data[i].categoryId == $("#Product_CategoryId").val()) {
                            document.getElementById("itemlist").innerHTML += listmaker(data[i].name, data[i].price, data[i].available, data[i].details, data[i].imagesName, data[i].id);
                           
                        }
                    });
                    $.each(data, function (j) {
                        if (data[j].categoryId == $("#Product_CategoryId").val()) {
                            $("#btn_" + data[j].id).on("click", function () {
                                saveToSession(data[j].id, $("#textbox_" + data[j].id).val(), data[j].price);
                                $("#textbox_" + data[j].id).val("");
                            });
                        }
                    });
                }
            });

        });
        function saveToSession(product_id, count, price) {
            order = new Object();
            order.productId = product_id;
            order.count = count;
            order.price = price;            
            $.ajax({
                url: "/Shopping/SaveInSession",
                type: "POST",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify(order),
                success: function() {                    
                    messages(product_id, "This product is Successfully Added", "#33ce1e");
                },
                error: function (jqXHR, exception) {
                    if (jqXHR.status == 200) {
                        messages(product_id, "This product is Successfully Added", "#33ce1e");
                    } else {
                        $("#message_" + product_id).text("An error occured");
                        $("#message_" + product_id).css('color', '#dd272a');
                    }
                  
                }
            });
        }
               
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

shop2/Views/Shopping/ShowOrders.cshtml
@model shop.ViewModels.OrdersViewModel

@{
    ViewBag.Title = "ShowOrders";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>ShowOrders</h2>
<table id="orders" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Row Number</th>
            <th>Product Name</th>
            <th>Product Price</th>
            <th>Number Of Product</th>
            <th>Total price</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Orders.Count(); i++)
        {
            <tr>
                <th>@{int row = i + 1; @row}</th>
                <th>@Model.ProductsName.ElementAt(i)</th>
                <th>@Model.Orders.ElementAt(i).Price</th>
                <th>@Model.Orders.ElementAt(i).Count</th>
                <th>@{double rowTotal = (Model.Orders.ElementAt(i).Count) * (Model.Orders.ElementAt(i).Price); @rowTotal}</th>
            </tr>
        }
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th>
                Total: @{double total = 0;
                    for (int j = 0; j < Model.Orders.Count(); j++)
                    {
                        total += (Model.Orders.ElementAt(j).Count) * (Model.Orders.ElementAt(j).Price);
                    }
                    @total
                }
            </th>
        </tr>
    </tbody>
</table>
<br />  
<button id="confirmOrder"> Confirm Order</button>

@section scripts{
    <script>
        $("#confirmOrder").on("click", function (e) {               
           window.location.href = '@Url.Action("SaveOrdersInDB", "Shopping")' ;           
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}